### ISSUE TITLE
Setup files and folder

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/todo-app-js#1]
### Tasks

- [x] HTML, CSS, JS files
- [x] import Bootstrap
- [x] import jQuery
- [x] pick google font
- [x] investigate usage of fontawesome
- [x] pick colour scheme
